
server:
  port: 9999
  servlet:
    context-path: /cache-demo


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/cache_demo?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: localhost
    port: 6379
    database: 0
    password:

mybatis:
  mapper-locations: mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true